version: "3"
services:

  # db:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: wiki
  #     POSTGRES_PASSWORD: wikijsrocks
  #     POSTGRES_USER: wikijs
  #   logging:
  #     driver: "none"
  #   restart: unless-stopped
  #   volumes:
  #     - db-data:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:2
    # depends_on:
    #   - db
    environment:
      DB_TYPE: postgres
      DB_HOST: 172.27.203.158
      DB_PORT: 5432
      DB_USER: chino
      DB_PASS: Chino1987*
      DB_NAME: wiki_chino
    restart: unless-stopped
    ports:
      - "80:3000"

volumes:
  db-data: